export const PRODUCTS_RECEIVED = 'PRODUCTS_RECEIVED';
export const PRODUCT_ADDED = 'PRODUCT_ADDED';
export const PRODUCT_EDITED = 'PRODUCT_EDITED';
export const PRODUCT_DELETED = 'PRODUCT_DELETED';

export const CART_ITEMS_RECEIVED = 'CART_ITEMS_RECEIVED';
export const CART_ITEM_ADDED = 'CART_ITEM_ADDED';
export const CHECKOUT = 'CHECKOUT';
